import type { PricingPlan } from "./types"

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: "free",
    name: "Free",
    description: "Basic access to get started on your professional journey",
    monthlyPrice: 0,
    yearlyPrice: 0,
    features: [
      { name: "Basic profile creation", included: true },
      { name: "Limited networking", included: true },
      { name: "Basic messaging (10/day)", included: true },
      { name: "View public content", included: true },
      { name: "Limited access to Build tab", included: true },
      { name: "Community forum access", included: true },
      { name: "Basic analytics", included: false },
      { name: "Video uploads", included: false },
      { name: "Mentorship features", included: false },
      { name: "Team collaboration", included: false },
    ],
    callToAction: "Get Started",
  },
  {
    id: "creator",
    name: "Creator+",
    description: "Perfect for content creators and influencers",
    badge: "Best for Creators",
    monthlyPrice: 9000,
    yearlyPrice: 97200, // 10% discount
    features: [
      { name: "Everything in Free", included: true },
      { name: "Unlimited messaging", included: true },
      { name: "Video content uploads", included: true, highlight: true },
      { name: "Creator analytics dashboard", included: true, highlight: true },
      { name: "Creator rewards program", included: true, highlight: true },
      { name: "Content monetization tools", included: true },
      { name: "Priority content visibility", included: true },
      { name: "Custom profile themes", included: true },
      { name: "Limited mentorship features", included: false },
      { name: "Team collaboration tools", included: false },
    ],
    callToAction: "Subscribe",
    popular: true,
  },
  {
    id: "mentor",
    name: "Mentor Pass",
    description: "Designed for professionals offering mentorship",
    badge: "Best for Mentors",
    monthlyPrice: 12000,
    yearlyPrice: 129600, // 10% discount
    features: [
      { name: "Everything in Creator+", included: true },
      { name: "Verified mentor badge", included: true, highlight: true },
      { name: "Mentorship marketplace access", included: true, highlight: true },
      { name: "Calendar booking system", included: true, highlight: true },
      { name: "Mentorship analytics", included: true },
      { name: "Client management tools", included: true },
      { name: "Customizable mentorship packages", included: true },
      { name: "Featured in mentor directory", included: true },
      { name: "Advanced team collaboration", included: false },
      { name: "Build tab premium features", included: false },
    ],
    callToAction: "Subscribe",
  },
  {
    id: "builder",
    name: "Builder Pro",
    description: "Full suite of tools for project collaboration",
    badge: "Best Value",
    monthlyPrice: 10000,
    yearlyPrice: 108000, // 10% discount
    features: [
      { name: "Everything in Free", included: true },
      { name: "Unlimited messaging", included: true },
      { name: "Full access to Build tab", included: true, highlight: true },
      { name: "Team collaboration tools", included: true, highlight: true },
      { name: "Project management features", included: true, highlight: true },
      { name: "Advanced analytics", included: true },
      { name: "Custom project templates", included: true },
      { name: "Priority support", included: true },
      { name: "Video uploads (limited)", included: true },
      { name: "Basic mentorship features", included: true },
    ],
    callToAction: "Subscribe",
  },
]
